[package]
name = "scrape"
version = "0.1.0"
edition = "2024"

[dependencies]
item-core = { git = "https://github.com/blitzfilter/item-core", branch = "main" }
item-read = { git = "https://github.com/blitzfilter/item-read", branch = "main" }
reqwest = { version = "0.12.15", features = ["json"] }
tokio = { version = "1", features = ["full"] }
async-trait = { version = "0.1.88" }
serde = { version = "1.0.219", features = ["derive"] }
aws-sdk-dynamodb = { version = "1.71.1" }
aws-sdk-sqs = { version = "1.64.0" }