[package]
name = "scrape"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.15", features = ["blocking", "json"] }
scraper = { version = "0.23.1" }
tokio = { version = "1", features = ["full"] }
futures = { version =  "0.3.31" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140" }