[package]
name = "scrape"
version = "0.1.0"
edition = "2024"

[dependencies]
item = { git = "https://github.com/blitzfilter/item", branch = "main" }
reqwest = { version = "0.12.15", features = ["json"] }
tokio = { version = "1", features = ["full"] }
async-trait = { version = "0.1.88" }