[package]
name = "scrape"
version = "0.1.0"
edition = "2024"

[dependencies]
item-core = { git = "https://github.com/blitzfilter/item-core", rev = "fc8bc203cfc21cdbda0704eae2cdd2742dfae2d9" }
item-read = { git = "https://github.com/blitzfilter/item-read", rev = "8654c30f5fffa9259d39b413ec92070c9fcd9916" }
reqwest = { version = "0.12.15", features = ["json"] }
tokio = { version = "1", features = ["full"] }
async-trait = { version = "0.1.88" }
serde = { version = "1.0.219", features = ["derive"] }
aws-config = { version = "1.6.1"}
aws-sdk-dynamodb = { version = "1.71.1" }
serde_dynamo = { version = "4.2.14", features = ["aws-sdk-dynamodb+1"] }