[package]
name = "scrape"
version = "0.1.0"
edition = "2024"

[dependencies]
item = { git = "https://github.com/blitzfilter/item", rev = "626ade9e407bdb7d9f0f3429ef162c4631e3d42d" }
reqwest = { version = "0.12.15", features = ["json"] }
tokio = { version = "1", features = ["full"] }
async-trait = { version = "0.1.88" }
strum = { version = "0.27.1" }
strum_macros = { version = "0.27.1" }
serde = { version = "1.0.219", features = ["derive"] }
