[package]
name = "scrape"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.15", features = ["json"] }
scraper = { version = "0.23.1" }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140" }
strum = { version = "0.27.1" }
strum_macros = { version = "0.27.1" }
blake3 = { version = "1.8.1" }